"""Synthetic energy market data generator for testing and development.

Generates realistic-looking data that mimics the patterns found in real
European electricity markets:
- Day-ahead prices with daily patterns (peak/off-peak), weekly seasonality,
  occasional negative prices, and rare spikes
- Renewable generation with solar daily cycle and wind variability
- Load with daily pattern (low at night, peak midday/evening)
- Intraday price deviations from day-ahead

This is NOT for production use — it's for unit tests and development when
API access is unavailable (e.g., no network, no API key, CI pipeline).

Calibration targets (approximate, based on German 2020-2023 data):
- DA price mean: ~50-80 EUR/MWh, std: ~30 EUR/MWh
- Wind capacity: ~60 GW installed, capacity factor ~20-35%
- Solar capacity: ~60 GW installed, capacity factor ~10-15% (annual avg)
- Load: ~40-80 GW range
"""

import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from typing import Annotated, Optional
import random

from .energy_utils import CET


def _get_day_type(date_str: str) -> str:
    """Determine if a day is weekday, saturday, or sunday."""
    dt = datetime.strptime(date_str, "%Y-%m-%d")
    weekday = dt.weekday()
    if weekday < 5:
        return "weekday"
    elif weekday == 5:
        return "saturday"
    else:
        return "sunday"


def _generate_hourly_pattern(hours: int, peak_hour: int, peak_value: float, base_value: float) -> np.ndarray:
    """Generate a daily pattern with peak at specified hour."""
    pattern = np.zeros(hours)
    for h in range(hours):
        dist_from_peak = abs(h - peak_hour)
        pattern[h] = base_value + (peak_value - base_value) * np.exp(-0.1 * dist_from_peak)
    return pattern


def generate_day_ahead_prices(
    delivery_date: Annotated[str, "Date in YYYY-MM-DD format"],
    market_area: Annotated[str, "Bidding zone"] = "DE-LU",
    seed: Optional[int] = None,
) -> str:
    """Generate synthetic day-ahead prices for 24 hours.

    Features:
    - Daily shape: lower at night (hours 0-5), peak midday (10-14) and evening (18-20)
    - Weekend effect: lower prices on weekends
    - Random component with occasional negative prices (5% chance per hour)
    - Rare spikes (1% chance per hour, up to 5x normal)
    """
    if seed is not None:
        np.random.seed(seed)
        random.seed(seed)

    day_type = _get_day_type(delivery_date)

    base_prices = {
        "weekday": 60.0,
        "saturday": 45.0,
        "sunday": 40.0,
    }
    base = base_prices.get(day_type, 60.0)

    daily_pattern = _generate_hourly_pattern(24, 18, base * 1.3, base * 0.7)

    prices = daily_pattern.copy()
    prices += np.random.normal(0, 8, 24)

    for i in range(24):
        if np.random.random() < 0.05:
            prices[i] = -abs(np.random.normal(5, 3))

        if np.random.random() < 0.01:
            prices[i] *= np.random.uniform(2, 5)

    prices = np.maximum(prices, -50)
    prices = np.minimum(prices, 500)

    df = pd.DataFrame({
        "Hour (CET)": [f"{h:02d}:00" for h in range(24)],
        "Price EUR/MWh": np.round(prices, 2),
    })

    header = f"# Synthetic Day-Ahead Prices for {market_area} on {delivery_date}\n"
    header += "# Generated by mock_energy.py (not real data)\n"
    header += "# Unit: EUR/MWh\n\n"

    return header + df.to_csv(index=False)


def generate_intraday_prices(
    delivery_date: Annotated[str, "Date in YYYY-MM-DD format"],
    market_area: Annotated[str, "Bidding zone"] = "DE-LU",
    seed: Optional[int] = None,
) -> str:
    """Generate synthetic intraday prices with deviations from day-ahead."""
    if seed is not None:
        np.random.seed(seed + 1)
        random.seed(seed + 1)

    df_da = generate_day_ahead_prices(delivery_date, market_area, seed=seed)
    lines = df_da.split("\n")
    da_prices = []
    for line in lines:
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        parts = line.split(",")
        if len(parts) >= 2:
            try:
                da_prices.append(float(parts[1]))
            except ValueError:
                continue

    intraday_prices = []
    for i, da_price in enumerate(da_prices[:24]):
        scale = abs(da_price) if da_price != 0 else 10.0
        deviation = np.random.normal(0, scale * 0.1)
        id_price = da_price + deviation

        if i >= 12:
            id_price *= 1.05

        intraday_prices.append(round(id_price, 2))

    df = pd.DataFrame({
        "Hour (CET)": [f"{h:02d}:00" for h in range(24)],
        "Intraday Price EUR/MWh": intraday_prices,
    })

    header = f"# Synthetic Intraday Prices for {market_area} on {delivery_date}\n"
    header += "# Generated by mock_energy.py (not real data)\n"
    header += "# Unit: EUR/MWh\n\n"

    return header + df.to_csv(index=False)


def generate_wind_solar_forecast(
    delivery_date: Annotated[str, "Date in YYYY-MM-DD format"],
    market_area: Annotated[str, "Bidding zone"] = "DE-LU",
    seed: Optional[int] = None,
) -> str:
    """Generate synthetic wind and solar generation forecasts."""
    if seed is not None:
        np.random.seed(seed + 2)
        random.seed(seed + 2)

    day_type = _get_day_type(delivery_date)

    solar_pattern = np.zeros(24)
    for h in range(24):
        if 6 <= h <= 19:
            solar_pattern[h] = np.sin(np.pi * (h - 6) / 13) * 55000

    wind_base = 15000 + 8000 * np.sin(np.linspace(0, 2 * np.pi, 24) + np.random.uniform(0, 2 * np.pi))
    wind_noise = np.random.normal(0, 3000, 24)
    wind_total = wind_base + wind_noise

    if day_type == "weekday":
        wind_total *= 1.1

    df = pd.DataFrame({
        "Hour (CET)": [f"{h:02d}:00" for h in range(24)],
        "Wind Onshore MW": np.round(np.maximum(wind_total * 0.8, 0), 0).astype(int),
        "Wind Offshore MW": np.round(np.maximum(wind_total * 0.2, 0), 0).astype(int),
        "Solar MW": np.round(solar_pattern, 0).astype(int),
        "Total Renewable MW": np.round(wind_total * 0.8 + solar_pattern, 0).astype(int),
    })

    header = f"# Synthetic Wind & Solar Forecast for {market_area} on {delivery_date}\n"
    header += "# Generated by mock_energy.py (not real data)\n"
    header += "# Unit: MW\n\n"

    return header + df.to_csv(index=False)


def generate_load_forecast(
    delivery_date: Annotated[str, "Date in YYYY-MM-DD format"],
    market_area: Annotated[str, "Bidding zone"] = "DE-LU",
    seed: Optional[int] = None,
) -> str:
    """Generate synthetic load forecast."""
    if seed is not None:
        np.random.seed(seed + 3)
        random.seed(seed + 3)

    day_type = _get_day_type(delivery_date)

    base_loads = {"weekday": 65000, "saturday": 55000, "sunday": 50000}
    base = base_loads.get(day_type, 65000)

    load_pattern = _generate_hourly_pattern(24, 10, base * 1.15, base * 0.7)
    load_pattern = _generate_hourly_pattern(24, 19, load_pattern.max() * 1.05, load_pattern.min())

    load = load_pattern + np.random.normal(0, 1500, 24)

    df = pd.DataFrame({
        "Hour (CET)": [f"{h:02d}:00" for h in range(24)],
        "Load Forecast MW": np.round(load, 0).astype(int),
    })

    header = f"# Synthetic Load Forecast for {market_area} on {delivery_date}\n"
    header += "# Generated by mock_energy.py (not real data)\n"
    header += "# Unit: MW\n\n"

    return header + df.to_csv(index=False)


def generate_residual_load(
    delivery_date: Annotated[str, "Date in YYYY-MM-DD format"],
    market_area: Annotated[str, "Bidding zone"] = "DE-LU",
    seed: Optional[int] = None,
) -> str:
    """Generate synthetic residual load (load - wind - solar)."""
    if seed is not None:
        np.random.seed(seed + 4)
        random.seed(seed + 4)

    df_load = generate_load_forecast(delivery_date, market_area, seed=seed)
    lines = df_load.split("\n")
    loads = []
    for line in lines:
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        parts = line.split(",")
        if len(parts) >= 2:
            try:
                loads.append(float(parts[1]))
            except ValueError:
                continue

    df_gen = generate_wind_solar_forecast(delivery_date, market_area, seed=seed)
    lines = df_gen.split("\n")
    renewables = []
    for line in lines:
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        parts = line.split(",")
        if len(parts) >= 4:
            try:
                renew = float(parts[1]) + float(parts[2]) + float(parts[3])
                renewables.append(renew)
            except ValueError:
                continue

    residual = []
    for i in range(24):
        load = loads[i] if i < len(loads) else 55000
        renew = renewables[i] if i < len(renewables) else 20000
        residual.append(max(load - renew, 5000))

    df = pd.DataFrame({
        "Hour (CET)": [f"{h:02d}:00" for h in range(24)],
        "Residual Load MW": np.round(residual, 0).astype(int),
    })

    header = f"# Synthetic Residual Load for {market_area} on {delivery_date}\n"
    header += "# Generated by mock_energy.py (not real data)\n"
    header += "# Unit: MW (Load - Wind - Solar)\n\n"

    return header + df.to_csv(index=False)


def generate_weather_forecast(
    delivery_date: Annotated[str, "Date in YYYY-MM-DD format"],
    market_area: Annotated[str, "Bidding zone"] = "DE-LU",
    seed: Optional[int] = None,
) -> str:
    """Generate synthetic weather data."""
    if seed is not None:
        np.random.seed(seed + 5)
        random.seed(seed + 5)

    temp_base = 15 + 10 * np.sin((datetime.strptime(delivery_date, "%Y-%m-%d").timetuple().tm_yday - 80) / 365 * 2 * np.pi)
    temperature = temp_base + np.random.normal(0, 3, 24)
    temperature = np.clip(temperature, -10, 35)

    cloud_base = np.random.randint(20, 80)
    clouds = cloud_base + np.random.randint(-20, 20, 24)
    clouds = np.clip(clouds, 0, 100)

    wind_speed = 5 + np.random.normal(0, 3, 24)
    wind_speed = np.clip(wind_speed, 0, 25)

    df = pd.DataFrame({
        "Hour (CET)": [f"{h:02d}:00" for h in range(24)],
        "Temperature °C": np.round(temperature, 1),
        "Cloud Cover %": np.round(clouds, 0).astype(int),
        "Wind Speed m/s": np.round(wind_speed, 1),
    })

    header = f"# Synthetic Weather for {market_area} on {delivery_date}\n"
    header += "# Generated by mock_energy.py (not real data)\n\n"

    return header + df.to_csv(index=False)